<form method="get" action="/adverts">
    <label>Комнат от
        <input name="kkv1" type="number" value="<?php echo $fields['kkv1'] ?>">
    </label>
    <br>
    <label>Комнат до
        <input name="kkv2" type="number" value="<?php echo $fields['kkv2'] ?>">
    </label>
    <br>
    <label>Цена от
        <input name="price1" type="number" value="<?php echo $fields['price1'] ?>">
    </label>
    <br>
    <label>Цена до
        <input name="price2" type="number" value="<?php echo $fields['price2'] ?>">
    </label>
    <br>
    <label>Метро
        <select name="metro[]" multiple>
            <?php foreach ($metro_stations as $key => $value): ?>
                <option value="<?php echo $key ?>"
                        <?php if (in_array($key, $fields['metro[]'])): ?>selected<?php endif; ?>><?php echo $value ?></option>
            <?php endforeach; ?>
        </select>
    </label>
    <br>
    <input type="submit" value="Найти">
</form>
