<table>
    <thead>
    <tr>
        <td>
            Кол-во комнат
        </td>
        <td>
            Адрес
        </td>
        <td>
            Район
        </td>
        <td>
            Этаж
        </td>
        <td>
            Тип дома
        </td>
        <td>
            Площадь (общая, жилая, кухня)
        </td>
        <td>
            Санузел
        </td>
        <td>
            Субъект
        </td>
        <td>
            Контакт
        </td>
        <td>
            Доп. сведения
        </td>
    </tr>
    </thead>
    <tbody>
    <?php include('list.phtml')?>
    </tbody>
</table>